### ISSUE TITLE
[ 1][t 4][2021-11-11][cuda.cpp:205]	[ GPU #3: bitcredit_setBlockTarget the provided PTX was compiled with an unsupported toolchain. ]

### ISSUE THREAD

**Issue by smith111707** [tontechio/pow-miner-gpu#40] opened 2021-11-11 15:55 UTC
subj

**Comment by tontechio** [comment] 2021-11-11 16:02
Duplicate of https://github.com/tontechio/pow-miner-gpu/issues/18

**Closed by tontechio** 2021-11-11 16:02 UTC
